### ISSUE TITLE
Initialize Repository

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.RaspberryPI.Playground#1]
**TODOs**
- [x] Initialize gitflow
- [x] Inform Marc to protect master branch and set develop branch as default
- [x] Set up C#/.NET project for Raspberry PI development
  - [x] Solution folder name: src
  - [x] Solution name equal to repository name
